<a href="https://colab.research.google.com/github/Romauld1990/PDA_SOL/blob/main/SAM2_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np
np.full (shape=7,  fill_value=7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np
array=np.arange(10, 101, 2)
print(array)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import numpy as np

# создаем массив из 10 случайных чисел в диапазоне от 0 до 100
arr = np.random.randint(0, 100, size=10)

# создаем новый список на каждой итерации цикла
reversed_array = list(set(arr))

# выводим массив на экран
print(reversed_array)

[33, 98, 1, 79, 80, 49, 50, 86, 94, 62]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
import numpy as np
x = np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np

# создаем матрицу размерностью 4x4
matrix = np.zeros((4, 4), dtype=int)

# заполняем матрицу единицами на диагонали, смещенной на один вверх
matrix[0][0] = 1
matrix[1][1] = 1
matrix[2][2] = 1
matrix[3][3] = 1

# выводим матрицу на экран
print(matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
import numpy as np

# создаем матрицу размерностью 4x4
matrix = np.zeros((4, 4), dtype=int)

# заполняем диагональ от 1 до 4, в другие ячейки прописываю 7
matrix[0][0] = 1
matrix[0][1] = 7
matrix[0][2] = 7
matrix[0][3] = 7
matrix[1][0] = 7
matrix[1][1] = 2
matrix[1][2] = 7
matrix[1][3] = 7
matrix[2][0] = 7
matrix[2][1] = 7
matrix[2][2] = 3
matrix[2][3] = 7
matrix[3][0] = 7
matrix[3][1] = 7
matrix[3][2] = 7
matrix[3][3] = 4

# выводим матрицу на экран
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np
x = np.zeros((5,5))
print(x)
# выводим матрицу размером 5*5
x += np.arange(5)
print(x)
# заполняем матрицу заданными значениями

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np

random_matrix = np.random.rand(10, 10)
# создаем матрицу 10*10
average_row = np.mean(random_matrix, axis=1)
# отнимаем среднее по строкам
print (random_matrix)

[[0.28131318 0.95306529 0.10071961 0.75700116 0.65182675 0.24785569
  0.49472513 0.24129658 0.43234627 0.41339018]
 [0.59813566 0.17292703 0.62928549 0.9102615  0.22530639 0.94317498
  0.32335902 0.49758968 0.2021     0.14946667]
 [0.70459577 0.69610506 0.29120521 0.73425149 0.28524397 0.09050932
  0.34174161 0.60284706 0.40859524 0.66680659]
 [0.79351862 0.38825291 0.18541407 0.70288648 0.47811439 0.2756301
  0.76596693 0.32221354 0.45083156 0.4158345 ]
 [0.39944264 0.98138774 0.58908064 0.53417226 0.07938449 0.60267745
  0.16978361 0.82526348 0.02935626 0.98645764]
 [0.09772149 0.46617479 0.91923651 0.89655942 0.97206579 0.85673407
  0.71997839 0.04722315 0.44611367 0.00909667]
 [0.19427525 0.04800703 0.99115638 0.35212641 0.39411007 0.48260487
  0.67729785 0.08288503 0.09804535 0.95443301]
 [0.72490508 0.7821141  0.53414599 0.59663871 0.41510749 0.43281286
  0.68233118 0.52070233 0.58375795 0.22555883]
 [0.97492341 0.44954999 0.25220765 0.37163845 0.53565101 0.01712099
  0.88095365 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [2]:
import numpy as np

# создаем матрицу случайных чисел размера 10 на 10
matrix = np.random.rand(10, 10)

# вычисляем медиану элементов каждого столбца
medians = np.median(matrix, axis=0)

# отнимаем медиану из каждого элемента столбца
result = matrix - medians

print(result)

[[ 0.07603863  0.67381233  0.28204394  0.21363692 -0.32528176 -0.05508172
  -0.10768398 -0.25199984 -0.45819372 -0.0503302 ]
 [-0.09285017  0.64814176  0.31534487  0.0295414   0.21752498  0.23806532
   0.12794813  0.07052178 -0.27098347  0.10450411]
 [ 0.59032811  0.00553235 -0.51630548  0.13494372  0.06028067  0.01629677
  -0.02035042 -0.4025123  -0.10048597 -0.05793685]
 [ 0.6398026  -0.21883765 -0.61029104  0.02757144  0.45437512 -0.33221995
  -0.2672813   0.40954582 -0.00363441  0.24318023]
 [-0.25505242  0.52475439 -0.25749583 -0.31103197 -0.0513591   0.13006326
   0.02035042  0.3363843   0.28935748  0.20460529]
 [ 0.01397597  0.49533622  0.34457747 -0.13366775 -0.063465    0.13648296
   0.34920571 -0.04911677  0.01033465 -0.36647975]
 [ 0.41377275 -0.00553235  0.03715004 -0.40321622  0.07181131  0.17883357
  -0.09987995 -0.30165545  0.1460815   0.10897289]
 [-0.07400756 -0.04798765 -0.03715004  0.17979573 -0.38621332 -0.01629677
   0.09205119  0.31225068  0.00363441  0.0503302 ]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [3]:
# Создание матрицы случайных чисел размера 10 на 10
matrix = np.random.randint(1, 10, (10, 10))
print("Исходная матрица:\n", matrix)

# Вычисление среднего значения для каждой строки
mean = np.mean(matrix, axis=1)

# Вычитание среднего значения из каждого элемента строки
matrix = matrix - mean.reshape(-1, 1)

print("Матрица после вычитания среднего значения по строкам:\n", matrix)

Исходная матрица:
 [[8 7 7 6 6 1 7 9 4 7]
 [2 5 8 2 8 5 8 6 4 3]
 [3 1 6 7 2 7 7 2 2 4]
 [3 2 4 9 9 5 4 8 3 4]
 [7 8 7 3 4 7 7 3 8 5]
 [8 3 2 2 5 3 7 2 7 9]
 [3 3 9 5 8 6 9 6 6 5]
 [1 6 8 3 8 1 2 9 2 5]
 [9 5 5 3 4 7 6 7 6 7]
 [5 9 1 6 9 5 9 3 2 4]]
Матрица после вычитания среднего значения по строкам:
 [[ 1.8  0.8  0.8 -0.2 -0.2 -5.2  0.8  2.8 -2.2  0.8]
 [-3.1 -0.1  2.9 -3.1  2.9 -0.1  2.9  0.9 -1.1 -2.1]
 [-1.1 -3.1  1.9  2.9 -2.1  2.9  2.9 -2.1 -2.1 -0.1]
 [-2.1 -3.1 -1.1  3.9  3.9 -0.1 -1.1  2.9 -2.1 -1.1]
 [ 1.1  2.1  1.1 -2.9 -1.9  1.1  1.1 -2.9  2.1 -0.9]
 [ 3.2 -1.8 -2.8 -2.8  0.2 -1.8  2.2 -2.8  2.2  4.2]
 [-3.  -3.   3.  -1.   2.   0.   3.   0.   0.  -1. ]
 [-3.5  1.5  3.5 -1.5  3.5 -3.5 -2.5  4.5 -2.5  0.5]
 [ 3.1 -0.9 -0.9 -2.9 -1.9  1.1  0.1  1.1  0.1  1.1]
 [-0.3  3.7 -4.3  0.7  3.7 -0.3  3.7 -2.3 -3.3 -1.3]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [8]:
import numpy as np

# Создаем вектор чисел от 1 до 51
v = np.arange(1, 52)

import numpy as np

# Создаем вектор чисел от 1 до 51
v = np.arange(1, 52)

# Создаем вектор нечетных чисел
odd_v = v[v%2 != 0]

# Создаем вектор четных чисел
even_v = v[v%2 == 0]

# Меняем размерности векторов
odd_m = odd_v.reshape((len(odd_v), 1))
even_m = even_v.reshape((len(even_v), 1))

# Находим произведение матриц
prod = np.dot(odd_m, even_m.T)

print(prod)

[[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  506  528  550]
 [  26   52   78  104  130  156  182  208  234  260  286  312  338  364
   390  416  442  468  494  520  546  572  598  624  650]
 [  30   60   90  120  150  180  210  240  270  300  330  360  390  420
   450  480  510  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [11]:
# создаем матрицу размерности 8x8
matrix = np.zeros((8, 8))

# заполняем диагональные элементы единицами
np.fill_diagonal(matrix, 1)

# заполняем элементы на четных строках и столбцах единицами
for i in range(0, 8, 2):
    for j in range(0, 8, 2):
        matrix[i][j+1] = 1
        matrix[i+1][j] = 1

print(matrix)

[[1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1.]]
